version: "3.7"

services:
  web:
    build: .
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    ports:
      - "4000:8000"

  mongo:
    image: mongo:4.4
    user: mongodb
    expose:
      - 27017
